FROM python:slim AS builder

EXPOSE 8080
WORKDIR /app

COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir

COPY . /app

CMD ["uvicorn", "main:app", "--reload", "--host=0.0.0.0", "--port=8080"]