FROM python:slim AS builder
ARG CACHEBUST=1

EXPOSE 8080
WORKDIR /app

COPY requirements.txt .
RUN python3 -m pip install -r requirements.txt --no-cache-dir

COPY . .

CMD ["python3", "app.py", "--host=0.0.0.0", "--port=8080"]