# syntax=docker/dockerfile:1.4

# FROM --platform=$BUILDPLATFORM python:3.7-alpine AS builder
FROM python:slim AS builder

EXPOSE 8080
WORKDIR /app 

COPY requirements.txt /app
RUN pip3 install -r requirements.txt --no-cache-dir

COPY . /app

ENTRYPOINT ["python3"]
CMD ["manage.py", "runserver", "0.0.0.0:8080"]